language: generic
services:
  - docker
node_js:
  - "12.13"
matrix:
    include:
      - os: linux
        dist: bionic
        sudo: required

if: branch = master

before_script:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install unzip; fi

script:
 - git stash --all
 - echo $(pwd)

after_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd ..; fi
  - cd Test-Suite
  - echo $(pwd)
  - git branch -a
  - git checkout remotes/origin/master
  - git status
  - bash ./generate_bc.sh
  - git clone https://github.com/mbarbar/crux-bitcode
  - cd crux-bitcode
  - rm pkgs.txt
  - echo -e "bc\nhtop" >> pkgs.txt
  - bash ./build-bitcode.sh
  - unzip -j -o \*.zip -d $TRAVIS_BUILD_DIR/test_cases_bc/crux-bc/
  - rm $TRAVIS_BUILD_DIR/test_cases_bc/crux-bc/info.txt
  - cd ..
  - git status
  - git add .
  - git commit -m'update bc files'
  - git push https://Wren71:${git_key}@github.com/SVF-tools/Test-Suite.git HEAD:master